# Generated by Django 5.0.1 on 2024-03-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Fecha_publicacion',
            field=models.DateTimeField(null=True),
        ),
    ]
