# Generated by Django 5.0.1 on 2024-03-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_post_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Fecha_evento',
            field=models.DateTimeField(null=True),
        ),
    ]
