# Generated by Django 5.0.1 on 2024-03-21 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_post_fecha_evento'),
    ]

    operations = [
    ]
