# Generated by Django 5.0.1 on 2024-04-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20240321_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lugar',
            field=models.TextField(default='camino bajo la petisa', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='organiza',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='paga',
            field=models.BooleanField(default=True),
        ),
    ]
