# Generated by Django 5.0.1 on 2024-04-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_post_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rental',
            field=models.BooleanField(null=True),
        ),
    ]
