# Generated by Django 5.0.1 on 2024-04-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_post_rental'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='paga',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rental',
        ),
        migrations.AddField(
            model_name='post',
            name='especificaciones',
            field=models.TextField(null=True),
        ),
    ]
